name: Test secrets 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Display Secrets for {{secrets.TESTPYPI_USER}} and {{secrets.TESTPYPI_PASSWORD}}
        run: |
          echo ${{secrets.TESTPYPI_USER}}
          echo ${{secrets.TESTPYPI_PASSWORD}}
          