name: test secrets 

on:
  push:
    branches:
      - WheelSupport
jobs:
  test secret job:
    runs-on: windows-latest
	steps:
	  - name: Test1
	    run: | 
		  echo $__token__ , $user and $password
          		  